### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Educational-Project** [rknaebel/discopy#21]
Installation problem with the new version 1.1.0
There is a long installation of dependencies installation, which doesn't give any results.
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/req_command.py", line 199, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py", line 319, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 128, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 384, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000

**Comment by rknaebel** [comment]
You cannot install the package or do you have problems installing the dependencies?
I have noticed problems with the recent Python3.9 version, too. Throughout the development, I have used Python3.7.
What version do you use?

**Comment by Educational-Project** [comment]
The problem appears during dependencies installation
I have Python 3.7.12
